# .github/workflows/assembla_doc_template.yml

name: Assembla Documento con Template

on:
  push:
    branches: [ main ]
    paths: 
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'
      - '**/*.sty'
      - '*.tex'
      - 'customPandoc.latex'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/sezioni/**'
      - 'config.yml'
      - '.github/scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kjarosh/latex:2025.1-small
      #image: ghcr.io/kjarosh/latex:2024.4-full

    steps:
    - name: Install git
      run: apk add --no-cache git

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install missing LaTeX packages     
      run: |
        #tlmgr option repository http://mirror.ctan.org/systems/texlive/tlnet
        tlmgr install authblk titlesec etoolbox fancyhdr geometry

    - name: Install Python + deps
      run: |
        apk add --no-cache python3 py3-pip bash git
        pip install --break-system-packages pyyaml python-liquid 

    - name: Processa i template con Python
      run: |
        rm -f README.md *.pdf
        python3 .github/scripts/process-template.py

    - name: Install Pandoc
      run: apk add --no-cache pandoc

    - name: Genera il PDF con Pandoc
      run: |
        TITLE=$(sed -n '/^---$/,/^---$/p' README.md | grep '^title:' | head -n1 | sed 's/title:[[:space:]]*//; s/^ *//; s/ *$//; s/[*]//g')
        SAFE_TITLE=$(echo "$TITLE" | tr ' ' '_' | tr -cd '[:alnum:]_')
        echo "Generazione PDF: $SAFE_TITLE.pdf"
        pandoc README.md -o "$SAFE_TITLE.pdf" \
          --pdf-engine=xelatex \
          --template=customPandoc.latex 

    - name: Commit del documento assemblato
      run: |
        cd "$GITHUB_WORKSPACE"
        ls -la
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -u
        git add README.md
        git diff --staged --quiet || git commit -m "Auto-aggiornamento documento con template [skip ci]"

    - uses: actions/upload-artifact@v4
      with:
        name: progetto
        path: "*.pdf"
        overwrite: true
        
    - name: Push delle modifiche
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
